#!/system/bin/sh

# pvrsrvinit isn't loading, fix it later though.
#/system/vendor/bin/pvrsrvinit

# SELinux isn't being very kind to us lately, but of course we're fixing that later.
#/system/bin/setenforce 0

/system/xbin/daemonsu --auto-daemon